### ISSUE TITLE
Error: Cannot find module '.../project/node_modules/bem-lib-site-view/desktop.bundles/index/index.bemtree'

### ISSUE THREAD

**Issue by ilyar** [bem-site/bem-lib-site-data#16]
Если поставить на уровне проекта:

``` bash
$ npm i -D bem-site/bem-lib-site-data
$ npm i -D bem-site/bem-lib-site-view
```

скопировать в проект реализацию  bem-lib-site:

``` bash
$ cp -r bem-lib-site/bin project
$ cp index.js project 
```

Получаю ошибку:

``` bash
$ ./bin/bem-lib-site .
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/user/project/node_modules/bem-lib-site-view/desktop.bundles/index/index.bemtree'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/user/project/node_modules/bem-lib-site-view/lib/process-blocks.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Важно отметить, что использовать дебаг при стили объявления переменных через один `var` невозможно, поправите если я не прав. Все меняется и дебаг становится возможным когда один `var` на одну перемененную.

**Comment by ilyar** [comment]
https://github.com/bem-site/bem-lib-site-view/issues/12
